[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Resume"
  url = "/castellanos.pdf"
  weight = 20

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 30

[[main]]
  name = "CPI Calculator"
  pageRef = "calculator"
  weight = 40

[[main]]
  name = "Mood"
  pageRef = "mood"
  weight = 50
